/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as ClientiRouteImport } from './routes/clienti'
import { Route as CommesseRouteImport } from './routes/commesse'
import { Route as ImpostazioniRouteImport } from './routes/impostazioni'
import { Route as FattureIndexRouteImport } from './routes/fatture.index'
import { Route as FattureIdRouteImport } from './routes/fatture.$id'
import { Route as PreventiviIndexRouteImport } from './routes/preventivi.index'
import { Route as PreventiviIdRouteImport } from './routes/preventivi.$id'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const ClientiRoute = ClientiRouteImport.update({
  id: '/clienti',
  path: '/clienti',
  getParentRoute: () => rootRouteImport,
} as any)
const CommesseRoute = CommesseRouteImport.update({
  id: '/commesse',
  path: '/commesse',
  getParentRoute: () => rootRouteImport,
} as any)
const ImpostazioniRoute = ImpostazioniRouteImport.update({
  id: '/impostazioni',
  path: '/impostazioni',
  getParentRoute: () => rootRouteImport,
} as any)
const FattureIndexRoute = FattureIndexRouteImport.update({
  id: '/fatture/',
  path: '/fatture/',
  getParentRoute: () => rootRouteImport,
} as any)
const FattureIdRoute = FattureIdRouteImport.update({
  id: '/fatture/$id',
  path: '/fatture/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const PreventiviIndexRoute = PreventiviIndexRouteImport.update({
  id: '/preventivi/',
  path: '/preventivi/',
  getParentRoute: () => rootRouteImport,
} as any)
const PreventiviIdRoute = PreventiviIdRouteImport.update({
  id: '/preventivi/$id',
  path: '/preventivi/$id',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/clienti': typeof ClientiRoute
  '/commesse': typeof CommesseRoute
  '/impostazioni': typeof ImpostazioniRoute
  '/fatture/$id': typeof FattureIdRoute
  '/preventivi/$id': typeof PreventiviIdRoute
  '/fatture/': typeof FattureIndexRoute
  '/preventivi/': typeof PreventiviIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/clienti': typeof ClientiRoute
  '/commesse': typeof CommesseRoute
  '/impostazioni': typeof ImpostazioniRoute
  '/fatture/$id': typeof FattureIdRoute
  '/preventivi/$id': typeof PreventiviIdRoute
  '/fatture': typeof FattureIndexRoute
  '/preventivi': typeof PreventiviIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/clienti': typeof ClientiRoute
  '/commesse': typeof CommesseRoute
  '/impostazioni': typeof ImpostazioniRoute
  '/fatture/$id': typeof FattureIdRoute
  '/preventivi/$id': typeof PreventiviIdRoute
  '/fatture/': typeof FattureIndexRoute
  '/preventivi/': typeof PreventiviIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/clienti'
    | '/commesse'
    | '/impostazioni'
    | '/fatture/$id'
    | '/preventivi/$id'
    | '/fatture/'
    | '/preventivi/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/clienti'
    | '/commesse'
    | '/impostazioni'
    | '/fatture/$id'
    | '/preventivi/$id'
    | '/fatture'
    | '/preventivi'
  id:
    | '__root__'
    | '/'
    | '/auth'
    | '/clienti'
    | '/commesse'
    | '/impostazioni'
    | '/fatture/$id'
    | '/preventivi/$id'
    | '/fatture/'
    | '/preventivi/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthRoute: typeof AuthRoute
  ClientiRoute: typeof ClientiRoute
  CommesseRoute: typeof CommesseRoute
  ImpostazioniRoute: typeof ImpostazioniRoute
  FattureIdRoute: typeof FattureIdRoute
  PreventiviIdRoute: typeof PreventiviIdRoute
  FattureIndexRoute: typeof FattureIndexRoute
  PreventiviIndexRoute: typeof PreventiviIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/clienti': {
      id: '/clienti'
      path: '/clienti'
      fullPath: '/clienti'
      preLoaderRoute: typeof ClientiRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/commesse': {
      id: '/commesse'
      path: '/commesse'
      fullPath: '/commesse'
      preLoaderRoute: typeof CommesseRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/impostazioni': {
      id: '/impostazioni'
      path: '/impostazioni'
      fullPath: '/impostazioni'
      preLoaderRoute: typeof ImpostazioniRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/fatture/': {
      id: '/fatture/'
      path: '/fatture'
      fullPath: '/fatture/'
      preLoaderRoute: typeof FattureIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/fatture/$id': {
      id: '/fatture/$id'
      path: '/fatture/$id'
      fullPath: '/fatture/$id'
      preLoaderRoute: typeof FattureIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/preventivi/': {
      id: '/preventivi/'
      path: '/preventivi'
      fullPath: '/preventivi/'
      preLoaderRoute: typeof PreventiviIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/preventivi/$id': {
      id: '/preventivi/$id'
      path: '/preventivi/$id'
      fullPath: '/preventivi/$id'
      preLoaderRoute: typeof PreventiviIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthRoute: AuthRoute,
  ClientiRoute: ClientiRoute,
  CommesseRoute: CommesseRoute,
  ImpostazioniRoute: ImpostazioniRoute,
  FattureIdRoute: FattureIdRoute,
  PreventiviIdRoute: PreventiviIdRoute,
  FattureIndexRoute: FattureIndexRoute,
  PreventiviIndexRoute: PreventiviIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
